### PR TITLE
Update branding related copy

### PR DESCRIPTION
**Pull request by matyax**
Updated copy.

Bonus: upgraded CircleCI config.

Closes https://github.com/VividCortex/artifacts/issues/4706.

### CODE REVIEW

**Comment by VikaCep** [comment]
Still says VividCortex here:

https://github.com/VividCortex/grunt-circleci/blob/a6049fdaffe628f8350c0edcb7528522a4e1e9cc/LICENSE#L3

**Comment by matyax** [comment]
@VikaCep here?

imagen

**Comment by VikaCep** [comment]
> @VikaCep here?
> 
> imagen

Made a wrong search and saw it there 🤦‍♀ apologies.

**Comment by matyax** [comment]
😄  no worries, I thought I missed one. Thanks!

**Pull request merged**
